### ISSUE TITLE
Prefix QI output in Engine Output dialog so the user knows what's what

### ISSUE THREAD

**Issue by SpiritQuaddicted** [hrehfeld/QuakeInjector#102]
The Quake Injector prints some lines into the Engine Output dialog by itself. Set some prefix to those so the user clearly knows which lines are engine output and which are QI. Best if you make it even version specific (BuildCommit).

**Comment by hrehfeld** [comment]
only very few lines are printed:

- https://github.com/hrehfeld/QuakeInjector/blob/master/src/de/haukerehfeld/quakeinjector/EngineOutputDialog.java#L79
- https://github.com/hrehfeld/QuakeInjector/blob/master/src/de/haukerehfeld/quakeinjector/EngineOutputDialog.java#L96
- https://github.com/hrehfeld/QuakeInjector/blob/master/src/de/haukerehfeld/quakeinjector/EngineOutputDialog.java#L99

Basically the first and the last line. So i would say it's pretty obvious. Or am I missing some prints here?

**Comment by SpiritQuaddicted** [comment]
Yes, it's a minor thing but I spend some time the other day pulling my hair on a line that ended up coming from the engine, not the Injector. I thought I had somehow mixed up sources locally...

**Comment by SpiritQuaddicted** [comment]
Solved by https://github.com/hrehfeld/QuakeInjector/commit/d65cfb3337e665827d21ce78a0047ce7c8f116e0
