### ISSUE TITLE
Multiple dependencies / additional files

### ISSUE THREAD

**Issue by negke** [hrehfeld/QuakeInjector#105]
The Injector and/or Quaddicted should allow for multiple depencies of a file (individual as well as in combination with other dependencies). An additional field or command to be set in each database entry that makes the Injector download and install ALL files required and/or specified for the particular release - for instance to automatically install available patches.

Example: Quoth -> additional file: quoth 2.2 patch. Downloading Quoth.zip will then automatically download and install quoth2pt2patch.zip as well (overwriting files as necessary).
If Quoth is the dependency: installing a Quoth-based map (from scratch), it downloads Quoth.zip and quoth2pt2patch.zip (therefore acknowleging the "dependency" of the dependency), and then installs the map into the Quoth directory.

**Comment by hrehfeld** [comment]
This should already be supported? https://github.com/hrehfeld/QuakeInjector/blob/master/src/de/haukerehfeld/quakeinjector/PackageDatabaseParser.java#L165

However, the correct way would be to support versions (ie. Quoth is just a pointer to Quoth2.2, but Quoth2.0 will also satisfy the dependency), which we do not.
