### ISSUE TITLE
Unable to set Quake and executable folder path

### ISSUE THREAD

**Issue by TheSilent96** [hrehfeld/QuakeInjector#108]
I'm on a iMac 3,1 GHz Intel Core i5, 8 GB DDR3 a 1333 MHz, AMD Radeon HD 6970M 1024 MB. I just installed QInjector for the first time, but the engine configurator won't  activate the buttons to confirm my choice(see attached).

I'm using Quakespasm.
Shouldn't be a permission issue, I already re-applied all of them to any file contained in /applications
![schermata 2016-10-18 alle 18 49 29](https://cloud.githubusercontent.com/assets/22918003/19488267/6585ade2-9566-11e6-9539-f438ec71b0ef.png)
![schermata 2016-10-18 alle 18 48 52](https://cloud.githubusercontent.com/assets/22918003/19488268/658d7932-9566-11e6-9991-2054267d7bd6.png)

.
I thought that QI may want my Quake folder to be installed in my user's applications instead of the computer's so I moved it. No cigar.

Totally stuck.

Any idea?

**Comment by hrehfeld** [comment]
We thought we had it fixed in #52 . What version of QI are you using?

**Comment by TheSilent96** [comment]
Oh, I did not see it. I did a bit of research before posting, but I'm new on GitHub, maybe I looked in the wrong places... 

Anyway, I'm using Alpha 2,downloaded half an hour ago from Quaddicted. The in app info says java 1.0, though...

**Comment by ericwa** [comment]
https://github.com/hrehfeld/QuakeInjector/pull/95 was only merged about a year ago, doesn't look like there is a release with that in it.

There was a discussion [here](https://www.quaddicted.com/forum/viewtopic.php?pid=715#p715) linking a special Mac build that I made several years ago, which was built from my master branch:
https://github.com/downloads/ericwa/QuakeInjector/Quake%20Injector.app.b52d4b059a7fd25fd0831e6c6929073d6d475e25.zip

@TheSilent96 might be worth trying that, until we make a new release of QI

**Comment by TheSilent96** [comment]
Sure thing, downloading right now, thanks a lot!!!!

**Comment by TheSilent96** [comment]
Even this don't seem to work. I downloaded it like 5 times, but keeps telling me the file is broken and should be moved to the trash upon launch...

**Comment by TheSilent96** [comment]
oh, well... guess I'll have to wait... Thanks anyway for your time!

**Comment by hrehfeld** [comment]
Oh my, there's a bug for that: #97 

For now, delete the downloaded file manually form the cache dir.
I'll close this, OK?

**Comment by TheSilent96** [comment]
OK, thanks.
The  [https://github.com/hrehfeld/QuakeInjector/issues/97] is about files downloaded with the Quake Injector, if I understand correctly. 

My problem was with the QI .app that you linked above. That fails constantly and has nothing to do with QI cache.

**Comment by hrehfeld** [comment]
Oh, then i misunderstood. Can you give a detailed report? What happened? What did you expect to happen?

**Comment by ericwa** [comment]
Sorry, it was just some special mac .app build I made years ago, that I linked earlier in the thread: https://github.com/hrehfeld/QuakeInjector/issues/108#issuecomment-254600741 Probably not worth troubleshooting.

@hrehfeld Should I make a release of the current master branch as`alpha-3`? master hasn't been updated since last year but it'll have this issue fixed

**Comment by hrehfeld** [comment]
Yes, that would be awesome!

ps. something was wrong with the email reply I sent, sorry for the delay!

**Comment by hrehfeld** [comment]
Yes, that would be awesome!

**Comment by ericwa** [comment]
@hrehfeld new release is up! https://github.com/hrehfeld/QuakeInjector/releases I just did `ant release` and uploaded the zip in the `release/` directory.
@TheSilent96 alpha03 should work on macOS. You just need to install the java 8 JRE if you don't have it already. (it should work on older Java versions too)

**Comment by hrehfeld** [comment]
Awesome, thank you!

**Comment by TheSilent96** [comment]
Great! Thanks Eric, off to try it out!!!

**Comment by ericwa** [comment]
Just tested alpha3 on macOS again and this is working, so I'll close this
