### ISSUE TITLE
Screenshots are broken

### ISSUE THREAD

**Issue by ericwa** [hrehfeld/QuakeInjector#110]
Tested on macOS 10.12 with both alpha02 and alpha03.
No screenshots are appearing for me. A grey box appears and then disappears after a second.
![screen shot 2016-10-25 at 4 08 16 pm](https://cloud.githubusercontent.com/assets/239161/19706113/74249928-9acd-11e6-8678-f13574d3c00b.png)

**Comment by ericwa** [comment]
Getting messages like:
```
Couldn't load image https://www.quaddicted.com/reviews/screenshots/3sarena_injector.jpg
```
That URL loads in Firefox, so it may be another java cert issue?

**Comment by hrehfeld** [comment]
Hmm, IIRC this happens when the app cannot connect to the server.
