### ISSUE TITLE
values for "hipnotic" and "rogue" checkboxes not saved

### ISSUE THREAD

**Issue by neogeographica** [hrehfeld/QuakeInjector#111]
They're not written to config.properties.

My guess right now is that this is because saveEngineConfig doesn't ever do RogueInstalled.set() or HipnoticInstalled.set(), and nor do its subroutines.

**Comment by SpiritQuaddicted** [comment]
Should be fixed thanks to @Warsen's contribution: https://github.com/hrehfeld/QuakeInjector/commit/2bd376352a5592853bafad1134410b04b6094433
