### ISSUE TITLE
font rendering looks like arse on Linux (fix supplied)

### ISSUE THREAD

**Issue by jmtd** [hrehfeld/QuakeInjector#113]
I hit this with [wadc](https://github.com/jmtd/wadc) too. The solution was to do something like this https://github.com/jmtd/wadc/commit/f89f6138364be8135733ed2c55e1a25d7386d586

(P.S. I borrowed some stuff from QuakeInjector for WadC: https://github.com/jmtd/wadc/commit/e675cd1284a25371a271042b0843c2ae6fe4d2d7 but I changed the file chooser to AWT which integrates better with OS filechoosers and doesn't suffer problems with Applications on OS X: https://github.com/jmtd/wadc/commit/a98cd2eae6f4a5c9d67667cb09f186278f914786. Thanks!)

**Comment by duganchen** [comment]
Setting the following before launching Quake Injector also works:
`
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'`

**Comment by SpiritQuaddicted** [comment]
Thanks, integrated in https://github.com/hrehfeld/QuakeInjector/commit/c896b7bcf2879c84631cd21dfb7533bd2827e2a4 !
