### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by SpiritQuaddicted** [hrehfeld/QuakeInjector#126]
I will try to do:

- [ ] Compile list of (user-facing) changes
- [ ] Finish https://github.com/hrehfeld/QuakeInjector/issues/68
- [ ] Build new version (alpha04?)
- [ ] Upload ZIP
- [ ] Make a news post about it

Anything else we need to do? Who can do these:

- [ ] Test on Linux(es), mostly different DEs are interesting I guess
- [ ] Test on Windows (modern 10, with modern Java?)
- [ ] Test on up-to-date MacOS

**Comment by WRFitch** [comment]
I'm happy to test on Ubuntu and Windows, depending on what exactly is needed

**Comment by SpiritQuaddicted** [comment]
Changes seems to boil down to:
- Random map button!
- Fixed UI scaling on high DPI displays
- Fixes completely broken download stuff

@WRFitch dunno, just see if it works for what you use it for :)
