### ISSUE TITLE
DPI settings

### ISSUE THREAD

**Issue by DoubleAgentDave** [hrehfeld/QuakeInjector#128]
Great program, but the text is miniscule on a high DPI display. I don't know how you have set it up but changing sun.java2d.uiScale or glass.gtk.uiScale give no results and so it's stuck to a small DPI so I'm left squinting at tiny text, (see https://wiki.archlinux.org/index.php/HiDPI#Java_applications for details on ArchLinux) Windows users are lucky as I guess they can set this using the file properties.
I'm using Manjaro with XFCE and openjdk version 1.8.0_265 with OpenJDK 64-Bit.
Cheers

**Comment by duganchen** [comment]
Try using Sun's Java and not OpenJDK. IIRC, Arch's howto works for Sun's Java.

**Comment by SpiritQuaddicted** [comment]
What makes you guess that the Java implementation causes this?

Screw Sun/Oracle. :)

**Comment by duganchen** [comment]
Anecdotal experience from tests with both Sun JDK and OpenJDK.

**Comment by SpiritQuaddicted** [comment]
Does it work fine with https://www.quaddicted.com/files/temp/quakeinjector-alpha03-17-gfb089bf.zip ?

**Comment by demoth** [comment]
It appears to be fixed according to this
https://bugs.openjdk.org/browse/JDK-8055212

How to use: set an environmental variable `GDK_SCALE=2` (or any other scale)

**Comment by DoubleAgentDave** [comment]
Yup :)
