### ISSUE TITLE
Project Site No Longer Resolves 

### ISSUE THREAD

**Issue by WRFitch** [hrehfeld/QuakeInjector#129]
http://www.haukerehfeld.de/projects/quakeinjector/ link no longer works, but https://haukerehfeld.de/projects/QuakeInjector/ does. Could this be updated in the sidebar please?

**Comment by SpiritQuaddicted** [comment]
Does not look like I can do that, @hrehfeld. Maybe https://www.quaddicted.com/tools/quake_injector?

**Comment by hrehfeld** [comment]
fixed.

**Comment by hrehfeld** [comment]
I don't think I can give you the rights to change this? You already have collaborator status.

**Comment by SpiritQuaddicted** [comment]
No clue! Should be fine :)
