### ISSUE TITLE
Fails to Launch

### ISSUE THREAD

**Issue by alicode1111** [hrehfeld/QuakeInjector#131]
I get this error when launching:
![image](https://user-images.githubusercontent.com/72287594/118378981-51b54e80-b5a5-11eb-851f-fa700d92fa7c.png)

Then this:
![image](https://user-images.githubusercontent.com/72287594/118378988-5974f300-b5a5-11eb-9e08-6e3f13355b26.png)

I think the issue is in the zip file, here's the warning 7zip gives me:
![image](https://user-images.githubusercontent.com/72287594/118379030-9d67f800-b5a5-11eb-807b-4995fbe6b049.png)

**Comment by SpiritQuaddicted** [comment]
What is your JDK and which version?

Does it also fail if you unzip using Windows' built-in archive unpacker?

**Comment by alicode1111** [comment]
Didn't have one earlier, but opening it with OpenJDK 11 does nothing
Will try with JDK now
