### ISSUE TITLE
Configuration files on GNU / Linux

### ISSUE THREAD

**Issue by alabarre** [hrehfeld/QuakeInjector#142]
I usually create links to binary files that do not come from a package in `~/bin/` which I include in `PATH` to be able to launch them from anywhere. 

This is a problem for QuakeInjector, because it stores its configuration in the directory from which it is launched. So launching it from, say, `~/Games/Quake/QuakeInjector` will store `config.properties`, `database.xml` and `installedMaps.xml` in `~/Games/Quake/QuakeInjector`, but launching it via the link I store in `~/bin/` will create new (and empty!) configuration files in `~/bin/` since the program cannot find the files it previously created.

Shouldn't QuakeInjector store its configuration in some fixed directory (say, `~/.quakeinjector/config/`) to avoid those problems?

**Comment by SpiritQuaddicted** [comment]
Definitely! It annoys me very much too and this should not be too hard to fix for someone who knows what they are doing (at least I hope it is easy in Java to get the appropriate directory with proper modern XDG support). There is an issue already: https://github.com/hrehfeld/QuakeInjector/issues/117
