### ISSUE TITLE
Remember column sorting

### ISSUE THREAD

**Issue by pokeshark** [hrehfeld/QuakeInjector#145]
I usually sort the content by Released (desc), but it is not saved on future sessions.

Would it be possible for sorting to be saved?

**Comment by SpiritQuaddicted** [comment]
I'd love that!

We have an older issue that includes this at https://github.com/hrehfeld/QuakeInjector/issues/53 but it had a title that made did not make it too obvious. I updated its title and will close this new issue in favor of it. Please just shout if you feel this should be kept open as separate issue :)
