### ISSUE TITLE
Quake Injector down for everyone? 

### ISSUE THREAD

**Issue by TheGrovetender** [hrehfeld/QuakeInjector#148]
I don't know how long Quake Injector has been down for, but for the last 2-3 weeks, it hasn't been pulling anything from Quaddicted, and installing maps gives me an error message. 
![image](https://github.com/hrehfeld/QuakeInjector/assets/166579196/d9844b01-78e6-4ef8-a4ac-bfa2963bd495)
![image](https://github.com/hrehfeld/QuakeInjector/assets/166579196/e5d154c0-3e1a-41d9-b911-1d5b8c921996)

There is a thread about this on r/quake and here on Github as well but no responses yet. 
https://www.reddit.com/r/quake/comments/1bwxq4n/quakeinjector_suddenly_cant_download_anything/

**Comment by SpiritQuaddicted** [comment]
Thank you for reporting this, this is the first time I hear of it. Unfortunately there does not seem to be an active maintainer of this project.

It sounds like there is something wrong with the certificate chain but https://www.ssllabs.com/ssltest/analyze.html?d=quaddicted.com&hideResults=on&latest shows no issues.

If anyone knows what causes this, your input would be highly appreciated. If it is something I can change server-side, I'd do it asap.

---

Including the plain text error message for discoverability: `PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

**Comment by dumptruckDS** [comment]
Confirming that the Java version displays the same error.

**Comment by jjelliott** [comment]
Pretty sure it's related to the certificate update on the 30th of March. Trying to figure out what a good resolution would be.

**Comment by jjelliott** [comment]
@SpiritQuaddicted Fix is pushed. Please review #149.
