### ISSUE TITLE
Failed to fetch current Database

### ISSUE THREAD

**Issue by Vanisch1103** [hrehfeld/QuakeInjector#151]
Hi everyone,

I now get this error. What can I do about it? re-downloaded and saved, same error,
Firewall is off, same error
![Unbenannt-1](https://github.com/user-attachments/assets/087ecb27-ecad-4e44-b87f-0dc2cd5ab70b)

**Comment by SpiritQuaddicted** [comment]
What exactly are you running? Which version? Where did you download it? How are you running it?

Both downloads from https://www.quaddicted.com/tools/quake_injector work fine here on Windows 10, the Java version with the latest release of https://adoptium.net/download/

**Comment by Vanisch1103** [comment]
Short info:

This error has now been fixed, but I don't know why. I think something went wrong with my internet connection as I also had problems with some downloads.

I have windows 11 Pro and the injector from the same link.

**Comment by SpiritQuaddicted** [comment]
Thanks! Maybe the server had a hiccup. :)
