### ISSUE TITLE
Show download status for each package in the detail panel

### ISSUE THREAD

**Issue by hrehfeld** [hrehfeld/QuakeInjector#47]
Show the download status of a package and possibly a 'redownload' button in the package detail panel.

**Comment by hrehfeld** [comment]
Why is this necessary? Install should just fail, and remove files, see #97

**Comment by SpiritQuaddicted** [comment]
I don't see this viable. While it might be handy to see which files might be cached locally, this is too brittle (users could delete files without QI knowing) and would add another column to the list.

Veto!
