### ISSUE TITLE
Change Database from YY to YYYY dates

### ISSUE THREAD

**Issue by SpiritQuaddicted** [hrehfeld/QuakeInjector#68]
Since the database serves the XML now, the date can be served as DD.MM.YYYY, just like the Injector would like it internally. Right now I serve it as DD.MM.YY and the Injector makes it YYYY internally. So to not break anything I serve it like that.

Only just before the next release remove the year forging in http://github.com/hrehfeld/QuakeInjector/blob/master/src/de/haukerehfeld/quakeinjector/PackageDatabaseParser.java#L203 and tell me to setup the right format for the XML.

**Comment by hrehfeld** [comment]
Status on this?

**Comment by SpiritQuaddicted** [comment]
Ready whenever we make a new release, it would break existing installations though. I could make it deliver different formats based on the user-agent but yuck!

**Comment by SpiritQuaddicted** [comment]
fixed server-side and in https://github.com/hrehfeld/QuakeInjector/commit/f62619d47bac28cac26c3d16007b25f01eab5ea8

older builds will report years in the 3800s and 3900s
