### ISSUE TITLE
Won't accept proper executable path

### ISSUE THREAD

**Issue by Jayman2000** [hrehfeld/QuakeInjector#98]
I'm running Linux Mint. When I try to enter in the path for the executable, Quake Injector says the the file doesn't exist. If i try to select it from the file selector dialog it changes from '/usr/games/quake' to '../../../games/quake', which aren't equivalent.

**Comment by hrehfeld** [comment]
It seems that the code is using this https://github.com/hrehfeld/QuakeInjector/blob/master/src/de/haukerehfeld/quakeinjector/EngineStarter.java#L62 check to determine if the file is valid

**Comment by neogeographica** [comment]
If @Jayman2000 is getting the "Doesn't exist!" popup, then in both the old-code and new-code cases that indicates that exists() is returning false on that file. Hard to see why that would fail; maybe the ball is being dropped somewhere in how a manually-entered path is converted to a File.

As for the conversion to a relative path, that looks like a thing that QuakeInjector is explicitly doing with configured paths. I don't know the rationale there though.

**Comment by hrehfeld** [comment]
IIRC the relative path is so that you can move your quake dir without adjusting *both* paths, it can automatically adjust the path to the new dir. Not sure if it makes that much sense, but I remember it had a proper reason when i implemented it. (check where the relative path is used..)

**Comment by SpiritQuaddicted** [comment]
Moving the directory seems like a super rare use-case...

Maybe it was meant as "nicely displaying just the filename" as on Windows it would usually be Engine.exe?

**Comment by hrehfeld** [comment]
Pretty sure there was a good reason when i put it in :-) (damnit why didn't i comment? :/)

**Comment by Jayman2000** [comment]
Is this bug still present? I just tested `alpha03`, and the path I selected was converted to a relative path properly.

**Comment by SpiritQuaddicted** [comment]
Let's close this then, if someone can reproduce it again, feel free to re-open. :)
